### ISSUE TITLE
Handshake failed with fatal error SSL_ERROR_SSL

### ISSUE THREAD

**Issue by boerninator** [Clarifai/clarifai-python-grpc#41]
Hello, 

I tried using the clarify-python-grpc client and it worked great. Today I tried the same script and I get this error: 

```
E1004 14:07:49.389861000 8636689920 ssl_transport_security.cc:1469]    Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E1004 14:07:49.629743000 8636689920 ssl_transport_security.cc:1469]    Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E1004 14:07:49.851189000 8636689920 ssl_transport_security.cc:1469]    Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
Traceback (most recent call last):
  File "/Users/Test_Pys/211003_test.py", line 40, in <module>
    post_model_outputs_response = stub.PostModelOutputs(
  File "/Users/opt/anaconda3/envs/testing/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/opt/anaconda3/envs/testing/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1633349269.851731000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3159,"referenced_errors":[{"created":"@1633349269.851729000","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":147,"grpc_status":14}]}"
```

What can I do to fix this?

**Comment by MichaelDanielTom** [comment]
[This ended](https://github.com/grpc/grpc/issues/27532#issuecomment-934006042) up working for me as a quick fix.

It looks like [an update to the grpc certs has been merged](https://github.com/grpc/grpc/pull/27539), but isn't in pypi yet.

**Comment by Igor-Shabalin** [comment]
i have the same problem

**Comment by johntorcivia** [comment]
This is fixed with an updated version of grpc.  This was a grpc / letsencrypt issue which has now been resolved.
